# TCL File Generated by Component Editor 18.1
# Fri Jun 05 18:36:38 CST 2026
# DO NOT MODIFY


# 
# audio_sample_input_hw "audio_sample_input_hw" v1.0
#  2026.06.05.18:36:38
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module audio_sample_input_hw
# 
set_module_property DESCRIPTION ""
set_module_property NAME audio_sample_input_hw
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME audio_sample_input_hw
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AudioSampleInputAvalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file AudioSampleInputAvalon.sv SYSTEM_VERILOG PATH Filtros/AudioSampleInputAvalon.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter FIFO_ADDR_WIDTH STRING 10
set_parameter_property FIFO_ADDR_WIDTH DEFAULT_VALUE 10
set_parameter_property FIFO_ADDR_WIDTH DISPLAY_NAME FIFO_ADDR_WIDTH
set_parameter_property FIFO_ADDR_WIDTH TYPE STRING
set_parameter_property FIFO_ADDR_WIDTH UNITS None
set_parameter_property FIFO_ADDR_WIDTH HDL_PARAMETER true
add_parameter FIFO_DEPTH STRING 1024
set_parameter_property FIFO_DEPTH DEFAULT_VALUE 1024
set_parameter_property FIFO_DEPTH DISPLAY_NAME FIFO_DEPTH
set_parameter_property FIFO_DEPTH TYPE STRING
set_parameter_property FIFO_DEPTH UNITS None
set_parameter_property FIFO_DEPTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_chipselect chipselect Input 1
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_address address Input 2
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point sample_clock
# 
add_interface sample_clock clock end
set_interface_property sample_clock clockRate 0
set_interface_property sample_clock ENABLED true
set_interface_property sample_clock EXPORT_OF ""
set_interface_property sample_clock PORT_NAME_MAP ""
set_interface_property sample_clock CMSIS_SVD_VARIABLES ""
set_interface_property sample_clock SVD_ADDRESS_GROUP ""

add_interface_port sample_clock sample_clock clk Input 1


# 
# connection point audio_sample
# 
add_interface audio_sample conduit end
set_interface_property audio_sample associatedClock clock
set_interface_property audio_sample associatedReset ""
set_interface_property audio_sample ENABLED true
set_interface_property audio_sample EXPORT_OF ""
set_interface_property audio_sample PORT_NAME_MAP ""
set_interface_property audio_sample CMSIS_SVD_VARIABLES ""
set_interface_property audio_sample SVD_ADDRESS_GROUP ""

add_interface_port audio_sample sample_request sample_request Input 1
add_interface_port audio_sample sample_out sample_out Output 16
add_interface_port audio_sample sample_out_valid sample_out_valid Output 1
add_interface_port audio_sample fifo_full fifo_full Output 1
add_interface_port audio_sample fifo_empty fifo_empty Output 1


# 
# connection point sample_reset
# 
add_interface sample_reset reset end
set_interface_property sample_reset associatedClock sample_clock
set_interface_property sample_reset synchronousEdges DEASSERT
set_interface_property sample_reset ENABLED true
set_interface_property sample_reset EXPORT_OF ""
set_interface_property sample_reset PORT_NAME_MAP ""
set_interface_property sample_reset CMSIS_SVD_VARIABLES ""
set_interface_property sample_reset SVD_ADDRESS_GROUP ""

add_interface_port sample_reset sample_reset reset Input 1

